datauri/__init__.py,sha256=4E-az_dmKBZerxH2C__s7MtIDdjOB9XaEmePafBwUvo,4770
datauri/exceptions.py,sha256=kLO34fwvf2RtQINizi7iUTVhaRJwvJCgVWUyxkfRPB4,134
python_datauri-1.2.1.dist-info/LICENSE,sha256=fhLl30uuEsshWBuhV87SDhmGoFCN0Q0Oikq5pM-U6Fw,1211
python_datauri-1.2.1.dist-info/WHEEL,sha256=vVCvjcmxuUltf8cYhJ0sJMRDLr1XsPuxEId8YDzbyCY,88
python_datauri-1.2.1.dist-info/METADATA,sha256=YKyDjN-8tEAHpstQnxocnXBYLtpvV__pmELyzAGDIvY,2680
python_datauri-1.2.1.dist-info/RECORD,,
